# Generated by Django 3.0.6 on 2020-05-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200524_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
